[mov-cli]
version = 1
player = "mpv"
debug = false
# parser = "lxml"
# editor = "nano"

[mov-cli.ui]
fzf = true

[mov-cli.plugins] # E.g: namespace = "package-name"
test = "mov-cli-test"

# [mov-cli.scrapers]
# default = "films"

# [mov-cli.http] # Don't mess with it if you don't know what you are doing!
# headers = { User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0" }

# [mov-cli.downloads] # Do not use backslashes use forward slashes
# save_path = "~/Downloads"
